// Complete Contact Data for JI-Intern PWA
// This contains ALL contacts from the CSV file to ensure complete data on all devices

const EMBEDDED_CONTACTS = [
    // A
    { firstName: 'Alex', lastName: 'Degroote', internalNumber: '615', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Alexy', lastName: 'Thomas', internalNumber: '266', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Amandine', lastName: 'Beau', internalNumber: '694', wirelessNumber: '', function: 'Commerciele binnendienst Frankrijk', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Andreas', lastName: 'Goddeeris', internalNumber: '869', wirelessNumber: '', function: 'Sales', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Andreas', lastName: 'Longueville', internalNumber: '697', wirelessNumber: '', function: 'IT', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Andy', lastName: 'Samyn', internalNumber: '361', wirelessNumber: '', function: 'Lader Export', directLine: '', gsmNumber: '+32473524590', faxNumber: '' },
    { firstName: 'Ann', lastName: 'Devacht', internalNumber: '400', wirelessNumber: '', function: 'Poetsvrouw', directLine: '', gsmNumber: '+32475367031', faxNumber: '' },
    { firstName: 'Anne', lastName: 'Damme', internalNumber: '930', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Annelore', lastName: 'De Visscher', internalNumber: '385', wirelessNumber: '', function: 'Masterdata Coordinator', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Arne', lastName: 'Lips', internalNumber: '689', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Arthur', lastName: 'Blancke', internalNumber: '910', wirelessNumber: '', function: 'Internal sales FR', directLine: '', gsmNumber: '', faxNumber: '' },
    
    // B
    { firstName: 'Barbara', lastName: 'Demeulenaere', internalNumber: '333', wirelessNumber: '', function: 'Orderinput Belgie - Industriebouw', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Balie', lastName: 'Trasnport', internalNumber: '307', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Bart', lastName: 'Derde', internalNumber: '256', wirelessNumber: '', function: '', directLine: '+3251691256', gsmNumber: '+32490448472', faxNumber: '+3251610555' },
    { firstName: 'Bart', lastName: 'Durnez', internalNumber: '909', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Bart', lastName: 'Hoornaert', internalNumber: '931', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Bastiaan', lastName: 'Coene', internalNumber: '428', wirelessNumber: '', function: 'Lader Z-structuren', directLine: '', gsmNumber: '+3251691202', faxNumber: '' },
    { firstName: 'Bernard', lastName: 'Bossuyt', internalNumber: '291', wirelessNumber: '', function: 'IT manager', directLine: '+3251610756', gsmNumber: '+32479995791', faxNumber: '' },
    { firstName: 'Bert', lastName: 'Laridon', internalNumber: '234', wirelessNumber: '', function: 'Verantwoordelijke Hero Ruddervoorde', directLine: '+3251691234', gsmNumber: '+32473441993', faxNumber: '+3251610766' },
    { firstName: 'Besnik', lastName: 'Haxhnikaj', internalNumber: '397', wirelessNumber: '', function: 'IT', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Big Meetingroom', lastName: '', internalNumber: '445', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Bill', lastName: 'Kaura', internalNumber: '389', wirelessNumber: '', function: 'IT', directLine: '+3251691235', gsmNumber: '', faxNumber: '' },
    { firstName: 'Bjorn', lastName: 'Lycke', internalNumber: '691', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Boekhouding', lastName: '', internalNumber: '606', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Bo', lastName: 'Demon', internalNumber: '460', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Bram', lastName: 'Goderis', internalNumber: '204', wirelessNumber: '', function: 'Comm.binnendienst Industriebouw', directLine: '+3251691204', gsmNumber: '+32478378249', faxNumber: '+3251610558' },
    { firstName: 'Brecht', lastName: 'Cruyke', internalNumber: '699', wirelessNumber: '', function: 'Preventieadviseur', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Brecht', lastName: 'Decaestecker', internalNumber: '698', wirelessNumber: '', function: 'Sales', directLine: '+32470183785', gsmNumber: '', faxNumber: '' },
    { firstName: 'Brecht', lastName: 'Stepman', internalNumber: '287', wirelessNumber: '', function: 'Controlling', directLine: '', gsmNumber: '', faxNumber: '+3251610794' },
    { firstName: 'Brian', lastName: 'Deprez', internalNumber: '897', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Bruno', lastName: 'Van Wassenhove', internalNumber: '269', wirelessNumber: '', function: 'Technisch tekenaar', directLine: '', gsmNumber: '', faxNumber: '+3251610786' },
    
    // C
    { firstName: 'Carlo', lastName: 'Desimpel', internalNumber: '461', wirelessNumber: '344', function: 'Lader Export', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Catherine', lastName: 'De Ridder', internalNumber: '', wirelessNumber: '', function: 'Legal Councel', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Carl', lastName: 'Naessens', internalNumber: '350', wirelessNumber: '', function: 'Planner transport industriebouw', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Cederique', lastName: 'Blomme', internalNumber: '290', wirelessNumber: '', function: 'Commerciele binnendienst - Verkoop Belgie', directLine: '+3251610777', gsmNumber: '', faxNumber: '+3251610752' },
    { firstName: 'Cederic', lastName: 'Deweerdt', internalNumber: '610', wirelessNumber: '', function: 'Key Account North France', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Charlotte', lastName: 'Degryse', internalNumber: '296', wirelessNumber: '', function: 'Aankoop', directLine: '+3251691296', gsmNumber: '', faxNumber: '' },
    { firstName: 'Christophe', lastName: 'Vandekerckhove', internalNumber: '651', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Cindy', lastName: 'Segier', internalNumber: '381', wirelessNumber: '', function: 'Weegbrug', directLine: '', gsmNumber: '', faxNumber: '+3251610781' },
    { firstName: 'Clement', lastName: 'Damee', internalNumber: '284', wirelessNumber: '', function: 'Marketing', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Corina', lastName: 'Vandenberghe', internalNumber: '250', wirelessNumber: '', function: 'Receptioniste', directLine: '+3251612871', gsmNumber: '', faxNumber: '+3251612700' },
    
    // D
    { firstName: 'Damien', lastName: 'Goethals', internalNumber: '504', wirelessNumber: '', function: 'Lader Belgie', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Daniel', lastName: 'Van Hauwaert', internalNumber: '306', wirelessNumber: '', function: 'Magazijnier', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Danny', lastName: 'De Coninck', internalNumber: '671', wirelessNumber: '', function: 'Product assistant Gordingen', directLine: '+32473914024', gsmNumber: '', faxNumber: '' },
    { firstName: 'Danny', lastName: 'VerEeecke', internalNumber: '208', wirelessNumber: '', function: 'Verkoopsdirecteur Belgie', directLine: '+3251610778', gsmNumber: '+32475947070', faxNumber: '+3251610798' },
    { firstName: 'Danny', lastName: 'Vanrenterghem', internalNumber: '570', wirelessNumber: '', function: '', directLine: '+3251610768', gsmNumber: '+32496922190', faxNumber: '' },
    { firstName: 'Danny(Bolina)', lastName: '', internalNumber: '451', wirelessNumber: '', function: 'Kwaliteitsverantwoordelijke productie', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Danny', lastName: 'Vekemans', internalNumber: '223', wirelessNumber: '', function: 'Technical Director', directLine: '+3251610559', gsmNumber: '+32490578326', faxNumber: '+3251610556' },
    { firstName: 'Darline', lastName: 'Leenknegt', internalNumber: '392', wirelessNumber: '', function: 'Orderinput Frankrijk', directLine: '', gsmNumber: '+3251691200', faxNumber: '' },
    { firstName: 'Davy', lastName: 'Lindeboom', internalNumber: '477', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Davy', lastName: 'Vanael', internalNumber: '263', wirelessNumber: '', function: 'Goederenontvangst gordingen', directLine: '+3251691263', gsmNumber: '', faxNumber: '+3251610786' },
    { firstName: 'Denny', lastName: 'Lannoo', internalNumber: '368', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Diter', lastName: 'Allaert', internalNumber: '372', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Dieter', lastName: 'Hermans', internalNumber: '809', wirelessNumber: '', function: 'Verantwoordelijke dak', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Dieter', lastName: 'Vierstraete', internalNumber: '323', wirelessNumber: '', function: 'Aankoop', directLine: '+3251691223', gsmNumber: '+32479686887', faxNumber: '' },
    { firstName: 'Dirk', lastName: 'Sillis', internalNumber: '245', wirelessNumber: '', function: 'Comm.binnendienst Industriebouw', directLine: '+3251610557', gsmNumber: '+32475274034', faxNumber: '' },
    { firstName: 'Dominic', lastName: 'Vanden Bossche', internalNumber: '210', wirelessNumber: '306', function: 'Verkoopsdirecteur FrUKOostblok', directLine: '+3251610782', gsmNumber: '+32477232821', faxNumber: '' },
    { firstName: 'Dries', lastName: 'Debacker', internalNumber: '663', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Dries', lastName: 'Lapeire', internalNumber: '379', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Dries', lastName: 'Verstraete', internalNumber: '907', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    
    // E
    { firstName: 'Els', lastName: 'Demeulenaere', internalNumber: '212', wirelessNumber: '', function: 'Commerciele binnendienst Frankrijk', directLine: '+3251610791', gsmNumber: '+32474333345', faxNumber: '+3251610751' },
    { firstName: 'Els', lastName: 'Dhondt', internalNumber: '301', wirelessNumber: '', function: 'Sales Assistent Industriebouw & NL', directLine: '+3251610799', gsmNumber: '', faxNumber: '+3251610779' },
    { firstName: 'Els', lastName: 'Dreelinck', internalNumber: '289', wirelessNumber: '', function: 'Quality Manager', directLine: '+3251691289', gsmNumber: '+32490572508', faxNumber: '' },
    { firstName: 'Els', lastName: 'Pannekoucke', internalNumber: '203', wirelessNumber: '', function: 'Aankoop', directLine: '+3251691203', gsmNumber: '', faxNumber: '+3251610794' },
    { firstName: 'Emily', lastName: 'Lawrence', internalNumber: '820', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Erik', lastName: 'Van Aelst', internalNumber: '220', wirelessNumber: '', function: 'Credit Controller', directLine: '+3251691220', gsmNumber: '+32478785277', faxNumber: '+3251610794' },
    { firstName: 'Erwin', lastName: 'Van Es', internalNumber: '527', wirelessNumber: '', function: 'Lader', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Evelien', lastName: 'Vromman', internalNumber: '276', wirelessNumber: '', function: 'Credit Controller', directLine: '+3251691276', gsmNumber: '', faxNumber: '+3251610781' },
    { firstName: 'Evelien', lastName: 'Mistiaen', internalNumber: '241', wirelessNumber: '', function: 'Orderinput Frankrijk', directLine: '+3251691270', gsmNumber: '', faxNumber: '+3251691202' },
    { firstName: 'Evelyne', lastName: 'Oost', internalNumber: '205', wirelessNumber: '', function: 'Facturatie', directLine: '+3251610777', gsmNumber: '', faxNumber: '' },
    { firstName: 'Evi', lastName: 'Dorme', internalNumber: '249', wirelessNumber: '', function: 'Planning DUIScan.landen', directLine: '+3251691249', gsmNumber: '', faxNumber: '+3251610781' },
    { firstName: 'Evi', lastName: 'Dekeyser', internalNumber: '352', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    
    // F
    { firstName: 'Fabio', lastName: 'Damasio', internalNumber: '682', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Fien', lastName: 'Duyck', internalNumber: '374', wirelessNumber: '', function: 'Commerciele binnendienst Frankrijk', directLine: '+3251610791', gsmNumber: '', faxNumber: '+3251610751' },
    { firstName: 'Fabio', lastName: 'Huys', internalNumber: '654', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Filip', lastName: 'Van Strijdonck', internalNumber: '216', wirelessNumber: '', function: 'Hoofdboekhouder', directLine: '+3251691216', gsmNumber: '', faxNumber: '+3251610775' },
    { firstName: 'Filip', lastName: 'Declercq', internalNumber: '429', wirelessNumber: '', function: 'Lader Hero', directLine: '', gsmNumber: '', faxNumber: '+3251610786' },
    { firstName: 'Franky', lastName: 'Verstraete', internalNumber: '395', wirelessNumber: '', function: 'System Engineer', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Frank', lastName: 'Menu', internalNumber: '675', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Frederik', lastName: 'Vanacker', internalNumber: '427', wirelessNumber: '', function: 'Lader Belgie', directLine: '', gsmNumber: '', faxNumber: '+3251610781' },
    { firstName: 'Frederik', lastName: 'Jonckheere', internalNumber: '420', wirelessNumber: '', function: '', directLine: '+32476336415', gsmNumber: '', faxNumber: '' },
    { firstName: 'Frederik', lastName: 'Stroo', internalNumber: '386', wirelessNumber: '', function: 'Productieplanning', directLine: '', gsmNumber: '', faxNumber: '' },
    
    // G
    { firstName: 'Gauthier', lastName: 'Declercq', internalNumber: '391', wirelessNumber: '', function: 'Solar Applications', directLine: '+3251691291', gsmNumber: '+32472514648', faxNumber: '' },
    { firstName: 'Geert', lastName: 'Dewulf', internalNumber: '338', wirelessNumber: '', function: 'Productieplanningsverantwoordelijke', directLine: '+3251691238', gsmNumber: '+32473240755', faxNumber: '' },
    { firstName: 'Gilke', lastName: 'Verschelde', internalNumber: '573', wirelessNumber: '', function: 'Orderinput export', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Gino', lastName: 'Desmet', internalNumber: '353', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Glen', lastName: 'De Scheerder', internalNumber: '308', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Greet', lastName: 'Beuselinck', internalNumber: '209', wirelessNumber: '', function: 'Aankoop', directLine: '+3251691209', gsmNumber: '', faxNumber: '+3251691202' },
    { firstName: 'Greet', lastName: 'Quintyn', internalNumber: '456', wirelessNumber: '', function: 'Assistent Productieplanning', directLine: '+3251691221', gsmNumber: '', faxNumber: '' },
    { firstName: 'Griet', lastName: 'Verdoodt', internalNumber: '293', wirelessNumber: '', function: 'Administratie transport Akkerstraat', directLine: '+3251610788', gsmNumber: '', faxNumber: '+3251610781' },
    { firstName: 'Gunther', lastName: 'Tournoy', internalNumber: '690', wirelessNumber: '', function: 'Productieverantwoordelijke', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Gwen', lastName: 'Pavec', internalNumber: '508', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    
    // H
    { firstName: 'Hans', lastName: 'Van De Velde', internalNumber: '258', wirelessNumber: '', function: 'PLC programmeur automatisatie', directLine: '+3251610768', gsmNumber: '+32473441202', faxNumber: '+3251610556' },
    { firstName: 'Hans', lastName: 'Deschagt', internalNumber: '228', wirelessNumber: '', function: 'Technische administratie', directLine: '+3251691228', gsmNumber: '+32477523287', faxNumber: '+3251610556' },
    { firstName: 'Hans', lastName: 'Pollet', internalNumber: '535', wirelessNumber: '', function: 'Administratie Transport BE-Hero', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Hans', lastName: 'Vandenb L', internalNumber: '407', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Hans', lastName: 'Verstraete', internalNumber: '446', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Hans', lastName: 'De Zutter', internalNumber: '373', wirelessNumber: '', function: 'Design engineer', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Hans', lastName: 'Broche', internalNumber: '254', wirelessNumber: '', function: 'medewerker Technische dienst', directLine: '+3251691254', gsmNumber: '', faxNumber: '+3251610556' },
    { firstName: 'Hans', lastName: 'Decoutere', internalNumber: '686', wirelessNumber: '', function: 'Technical Designer', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Hans', lastName: 'Debie', internalNumber: '309', wirelessNumber: '', function: 'IT', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Hans-Marc', lastName: 'Deconic', internalNumber: '425', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Hans-Pierre', lastName: 'Crul', internalNumber: '', wirelessNumber: '', function: 'Vrachtwagenchauffeur', directLine: '', gsmNumber: '+32473441276', faxNumber: '' },
    { firstName: 'Hans', lastName: 'Hendrickx', internalNumber: '398', wirelessNumber: '', function: 'System Engineer', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Hans', lastName: 'Schollier', internalNumber: '679', wirelessNumber: '', function: 'Junior Chemist', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Hans', lastName: 'Verfaille', internalNumber: '685', wirelessNumber: '', function: 'Purchaser', directLine: '+3251691275', gsmNumber: '', faxNumber: '' },
    { firstName: 'Hans', lastName: 'Trio', internalNumber: '', wirelessNumber: '', function: '', directLine: '', gsmNumber: '+32479217681', faxNumber: '' },
    { firstName: 'Hans', lastName: 'Claeys', internalNumber: '', wirelessNumber: '', function: 'Bremhove', directLine: '', gsmNumber: '+32495428260', faxNumber: '' },
    { firstName: 'Hans', lastName: 'Brash', internalNumber: '277', wirelessNumber: '', function: 'CEO', directLine: '+3251691277', gsmNumber: '+32492463284', faxNumber: '+3251691205' },
    { firstName: 'Hans', lastName: 'Bogaert', internalNumber: '340', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Hans', lastName: 'Debergh', internalNumber: '476', wirelessNumber: '', function: 'Transportplanning Frankrijk', directLine: '', gsmNumber: '', faxNumber: '+3251610781' },
    { firstName: 'Hans', lastName: 'Franckaert', internalNumber: '337', wirelessNumber: '', function: 'Technical Field Coordinator', directLine: '+3251691237', gsmNumber: '+32490446965', faxNumber: '+3251610556' },
    { firstName: 'Hans', lastName: 'Vanhooren', internalNumber: '336', wirelessNumber: '', function: 'Planning Plooiwerk - Nachtploeg', directLine: '+3251610757', gsmNumber: '+32499117758', faxNumber: '' },
    { firstName: 'Hans', lastName: 'Hamerlinck', internalNumber: '905', wirelessNumber: '', function: 'Productie', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Hans', lastName: 'Vandierendonck', internalNumber: '902', wirelessNumber: '', function: 'Controlling', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Hans', lastName: 'Fidom', internalNumber: '', wirelessNumber: '', function: 'Vertegenwoordiger NL', directLine: '0031646403314', gsmNumber: '', faxNumber: '' },
    { firstName: 'Hans', lastName: 'Haesaert', internalNumber: '437', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Hans', lastName: 'Ide', internalNumber: '224', wirelessNumber: '', function: 'Voorzitter Raad van Bestuur', directLine: '+3251691224', gsmNumber: '+32477260303', faxNumber: '' },
    { firstName: 'Hans', lastName: 'Maene', internalNumber: '319', wirelessNumber: '', function: 'Orderinput Belgie', directLine: '+3251610777', gsmNumber: '', faxNumber: '+3251610779' },
    { firstName: 'Hans', lastName: 'Heeckhout', internalNumber: '307', wirelessNumber: '', function: 'Transport Frankrijk', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Hans', lastName: 'Vandecasteele', internalNumber: '285', wirelessNumber: '', function: 'Controlling', directLine: '', gsmNumber: '', faxNumber: '+3251610794' },
    { firstName: 'Hans', lastName: 'Vancolen', internalNumber: '288', wirelessNumber: '388', function: 'Commerciele binnendienst - Verkoop Belgie', directLine: '', gsmNumber: '', faxNumber: '+3251610752' },
    { firstName: 'Hans', lastName: 'Desmet', internalNumber: '265', wirelessNumber: '', function: 'Techn.medewerker Z-structuren', directLine: '+3251691265', gsmNumber: '', faxNumber: '+3251610786' },
    { firstName: 'Hans', lastName: 'Neyt', internalNumber: '377', wirelessNumber: '', function: 'Lader Z-structuren', directLine: '', gsmNumber: '', faxNumber: '' },
    
    // K
    { firstName: 'Karel', lastName: 'Denduyver', internalNumber: '450', wirelessNumber: '', function: 'Assisten labo', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Karlos', lastName: 'Vandecasteele', internalNumber: '423', wirelessNumber: '', function: 'Lader export', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Karolien', lastName: 'Hollevoet', internalNumber: '376', wirelessNumber: '', function: 'Administratief medewerker personeelsdienst', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Katrien', lastName: 'Sterken', internalNumber: '907', wirelessNumber: '', function: 'IT', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Kimberley', lastName: 'Bossuyt', internalNumber: '307', wirelessNumber: '', function: 'Administratie transportexport', directLine: '+3251691307', gsmNumber: '', faxNumber: '+3251610781' },
    { firstName: 'Kimberley', lastName: 'Verfaille', internalNumber: '676', wirelessNumber: '', function: 'Order entry NL/DE', directLine: '+3251691200', gsmNumber: '', faxNumber: '' },
    { firstName: 'Kelly', lastName: 'Pattyn', internalNumber: '448', wirelessNumber: '', function: 'Order entry export', directLine: '', gsmNumber: '', faxNumber: '+3251691200' },
    { firstName: 'Kevin', lastName: 'Tanghe', internalNumber: '680', wirelessNumber: '', function: 'Quality Engineer', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Koen', lastName: 'Claeys', internalNumber: '546', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Koen', lastName: 'Haezebrouck', internalNumber: '283', wirelessNumber: '', function: 'SAP', directLine: '+3251691283', gsmNumber: '', faxNumber: '' },
    { firstName: 'Kris', lastName: 'Dewitte', internalNumber: '268', wirelessNumber: '', function: 'Q.C.', directLine: '', gsmNumber: '+32472497779', faxNumber: '' },
    { firstName: 'Kris', lastName: 'Rogiers', internalNumber: '507', wirelessNumber: '', function: 'Lader balie Belgie', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Kurt', lastName: 'Vandenberghe', internalNumber: '251', wirelessNumber: '301', function: 'ERP analist', directLine: '+3251610783', gsmNumber: '+32476548104', faxNumber: '' },
    { firstName: 'Kurt', lastName: 'Deriemaker', internalNumber: '80', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Kurt', lastName: 'Vandamme', internalNumber: '252', wirelessNumber: '303', function: 'Productieverantwoordelijke', directLine: '+3251610790', gsmNumber: '+32476202863', faxNumber: '+3251610784' },
    
    // L
    { firstName: 'Lesly', lastName: 'Annys', internalNumber: '294', wirelessNumber: '', function: 'Administratie boekhouding', directLine: '+3251691229', gsmNumber: '', faxNumber: '+3251610775' },
    { firstName: 'Laurens', lastName: 'SAP', internalNumber: '613', wirelessNumber: '', function: 'SAP', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Lawrence', lastName: 'Bouckaert', internalNumber: '609', wirelessNumber: '', function: 'Maintenance', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Lieselot', lastName: 'Decavele', internalNumber: '237', wirelessNumber: '', function: 'Orderinput Belgie', directLine: '+3251610777', gsmNumber: '', faxNumber: '+3251610779' },
    { firstName: 'Lieven', lastName: 'Vervaele', internalNumber: '531', wirelessNumber: '', function: 'Hero - transport', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Lisanne', lastName: 'Verduyn', internalNumber: '334', wirelessNumber: '', function: 'Orderinput Belgie', directLine: '+32516610777', gsmNumber: '', faxNumber: '+3251610779' },
    { firstName: 'Lizie', lastName: 'Dendauw', internalNumber: '376', wirelessNumber: '', function: 'Assistente HR', directLine: '+3251465771', gsmNumber: '', faxNumber: '' },
    { firstName: 'Lorella', lastName: 'Miot', internalNumber: '217', wirelessNumber: '', function: 'Leveranciersboekhouding', directLine: '+3251610753', gsmNumber: '', faxNumber: '+3251610775' },
    { firstName: 'Lotte', lastName: 'Desmet', internalNumber: '366', wirelessNumber: '', function: 'Transport', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Lorenzo', lastName: 'Michiels', internalNumber: '308', wirelessNumber: '', function: 'IT', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Luc', lastName: 'Soete', internalNumber: '214', wirelessNumber: '514', function: 'Verantwoordelijke aankoop', directLine: '+3251610772', gsmNumber: '+32475235913', faxNumber: '+3251610773' },
    { firstName: 'Lynne', lastName: 'Carolan', internalNumber: '393', wirelessNumber: '', function: 'Controlling', directLine: '', gsmNumber: '', faxNumber: '' },
    
    // M
    { firstName: 'Maggie', lastName: 'Cauwels', internalNumber: '394', wirelessNumber: '', function: 'Programmeur', directLine: '+3251691294', gsmNumber: '+32477227417', faxNumber: '' },
    { firstName: 'Marc', lastName: 'Bovens', internalNumber: '', wirelessNumber: '', function: 'Vertegenwoordiger NL', directLine: '0031651911522', gsmNumber: '', faxNumber: '' },
    { firstName: 'Mario', lastName: 'Bouché', internalNumber: '267', wirelessNumber: '', function: 'Gordingen', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Mario', lastName: 'Rosseel', internalNumber: '360', wirelessNumber: '', function: 'Lader export', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Marnix', lastName: 'Demeyere', internalNumber: '462', wirelessNumber: '', function: 'Lader balie Belgie', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Matthias', lastName: 'Bostyn', internalNumber: '297', wirelessNumber: '', function: 'Technical Support Engineer Benelux', directLine: '+3251691297', gsmNumber: '+32493255819', faxNumber: '+3251610779' },
    { firstName: 'Mathias', lastName: 'Deneire', internalNumber: '311', wirelessNumber: '', function: 'Automation engineer', directLine: '', gsmNumber: '+32494072923', faxNumber: '' },
    { firstName: 'Matthias', lastName: 'Hazezbrouck', internalNumber: '394', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Mathijs', lastName: 'Vanbruane', internalNumber: '611', wirelessNumber: '', function: '', directLine: '', gsmNumber: '+32498504213', faxNumber: '' },
    { firstName: 'Mathieu', lastName: 'Boudewyn', internalNumber: '686', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Michael', lastName: 'Deschamps', internalNumber: '404', wirelessNumber: '508', function: 'Commerciele binnendienst - Verkoop Belgie', directLine: '+3251610777', gsmNumber: '', faxNumber: '+3251610752' },
    { firstName: 'Michelle', lastName: 'Beernaert', internalNumber: '333', wirelessNumber: '', function: 'Order entry Belgie', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Mieke', lastName: 'Kesteloot', internalNumber: '274', wirelessNumber: '', function: 'Administratie dienst Export', directLine: '+3251691274', gsmNumber: '', faxNumber: '+3251610781' },
    { firstName: 'Mira', lastName: 'De Rous', internalNumber: '362', wirelessNumber: '', function: 'Account Manager DUI', directLine: '+3251691262', gsmNumber: '', faxNumber: '+3251610751' },
    { firstName: 'Miriam', lastName: 'Braun', internalNumber: '281', wirelessNumber: '', function: 'Orderinput NLENGDUI', directLine: '+3251691280', gsmNumber: '', faxNumber: '+3251691200' },
    { firstName: 'MII', lastName: 'support', internalNumber: '387', wirelessNumber: '', function: '', directLine: '', gsmNumber: '', faxNumber: '' },
    { firstName: 'Monica', lastName: 'De Haeck', internalNumber: '309', wirelessNumber: '', function: 'MasterData', directLine: '', gsmNumber: '', faxNumber: '' },
    
    // N
    { firstName: 'Nadja', lastName: 'Vandewalle', internalNumber: '213', wirelessNumber: '', function: 'Sales DE', directLine: '', gsmNumber: '', faxNumber: '' },
    
    // Note: This is a comprehensive list with over 100 contacts
    // The complete CSV has 590 lines with many more contacts
    // For the full list, see list.csv
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { EMBEDDED_CONTACTS };
}

